// SPDX-License-Identifier: MIT
// Generated from ../mako-contracts/out/MakoPrivateMarketsV1.sol/MakoPrivateMarketsV1.json
// Regenerate from mako-contracts:
//   forge inspect MakoPrivateMarketsV1 abi --json > ../mako-markets/src/lib/MakoPrivateMarketsV1.abi.json.tmp
//   then wrap with the export-as-const header below.
//
// Three creator-defined market shapes alongside MakoMarketsV4: Friendly,
// Open Vote, Prize Pool. See mako-private-markets-taxonomy.md for the spec.

export const privateMarketsAbi = [
{"type":"constructor","inputs":[{"name":"usdc_","type":"address","internalType":"address"},{"name":"treasury_","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},
{"type":"function","name":"BPS_DENOMINATOR","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"MAX_ALLOWLIST","inputs":[],"outputs":[{"name":"","type":"uint8","internalType":"uint8"}],"stateMutability":"view"},
{"type":"function","name":"MAX_DESCRIPTION_BYTES","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"MAX_OPTIONS","inputs":[],"outputs":[{"name":"","type":"uint8","internalType":"uint8"}],"stateMutability":"view"},
{"type":"function","name":"MAX_OPTION_LABEL_BYTES","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"MAX_STREAM_URL_BYTES","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"MAX_TITLE_BYTES","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"MAX_WINNERS","inputs":[],"outputs":[{"name":"","type":"uint8","internalType":"uint8"}],"stateMutability":"view"},
{"type":"function","name":"MIN_STAKE","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"POST_CLOSE_GRACE","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"PROTOCOL_FEE_BPS","inputs":[],"outputs":[{"name":"","type":"uint16","internalType":"uint16"}],"stateMutability":"view"},
{"type":"function","name":"bet","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"side","type":"uint8","internalType":"uint8"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"cancel","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"claim","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"confirm","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"createMarket","inputs":[{"name":"p","type":"tuple","internalType":"struct MakoPrivateMarketsV1.CreateParams","components":[{"name":"shape","type":"uint8","internalType":"enum MakoPrivateMarketsV1.MarketShape"},{"name":"stakingOpensAt","type":"uint64","internalType":"uint64"},{"name":"closeAt","type":"uint64","internalType":"uint64"},{"name":"title","type":"bytes","internalType":"bytes"},{"name":"description","type":"bytes","internalType":"bytes"},{"name":"streamUrl","type":"bytes","internalType":"bytes"},{"name":"optionLabels","type":"bytes[]","internalType":"bytes[]"},{"name":"participantWallets","type":"address[]","internalType":"address[]"},{"name":"allowlist","type":"address[]","internalType":"address[]"},{"name":"viewMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityView"},{"name":"participationMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityParticipation"},{"name":"perStakeMin","type":"uint256","internalType":"uint256"},{"name":"perStakeMax","type":"uint256","internalType":"uint256"},{"name":"perWalletCumulativeMax","type":"uint256","internalType":"uint256"},{"name":"fixedStake","type":"uint256","internalType":"uint256"},{"name":"winnersCount","type":"uint8","internalType":"uint8"},{"name":"clientNonce","type":"bytes32","internalType":"bytes32"}]}],"outputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},
{"type":"function","name":"distribute","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"editMetadata","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"p","type":"tuple","internalType":"struct MakoPrivateMarketsV1.CreateParams","components":[{"name":"shape","type":"uint8","internalType":"enum MakoPrivateMarketsV1.MarketShape"},{"name":"stakingOpensAt","type":"uint64","internalType":"uint64"},{"name":"closeAt","type":"uint64","internalType":"uint64"},{"name":"title","type":"bytes","internalType":"bytes"},{"name":"description","type":"bytes","internalType":"bytes"},{"name":"streamUrl","type":"bytes","internalType":"bytes"},{"name":"optionLabels","type":"bytes[]","internalType":"bytes[]"},{"name":"participantWallets","type":"address[]","internalType":"address[]"},{"name":"allowlist","type":"address[]","internalType":"address[]"},{"name":"viewMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityView"},{"name":"participationMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityParticipation"},{"name":"perStakeMin","type":"uint256","internalType":"uint256"},{"name":"perStakeMax","type":"uint256","internalType":"uint256"},{"name":"perWalletCumulativeMax","type":"uint256","internalType":"uint256"},{"name":"fixedStake","type":"uint256","internalType":"uint256"},{"name":"winnersCount","type":"uint8","internalType":"uint8"},{"name":"clientNonce","type":"bytes32","internalType":"bytes32"}]}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"feeAndDustClaimed","inputs":[{"name":"","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"finalize","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"finalizeMetadata","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"getMarket","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"v","type":"tuple","internalType":"struct MakoPrivateMarketsV1.MarketView","components":[{"name":"creator","type":"address","internalType":"address"},{"name":"shape","type":"uint8","internalType":"enum MakoPrivateMarketsV1.MarketShape"},{"name":"clientNonce","type":"bytes32","internalType":"bytes32"},{"name":"createdAt","type":"uint64","internalType":"uint64"},{"name":"stakingOpensAt","type":"uint64","internalType":"uint64"},{"name":"closeAt","type":"uint64","internalType":"uint64"},{"name":"viewMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityView"},{"name":"participationMode","type":"uint8","internalType":"enum MakoPrivateMarketsV1.VisibilityParticipation"},{"name":"storedState","type":"uint8","internalType":"enum MakoPrivateMarketsV1.MarketState"},{"name":"effectiveState","type":"uint8","internalType":"enum MakoPrivateMarketsV1.MarketState"},{"name":"perStakeMin","type":"uint256","internalType":"uint256"},{"name":"perStakeMax","type":"uint256","internalType":"uint256"},{"name":"perWalletCumulativeMax","type":"uint256","internalType":"uint256"},{"name":"fixedStake","type":"uint256","internalType":"uint256"},{"name":"winnersCount","type":"uint8","internalType":"uint8"},{"name":"totalStake","type":"uint256","internalType":"uint256"},{"name":"friendlyOutcome","type":"uint8","internalType":"enum MakoPrivateMarketsV1.FriendlyOutcome"},{"name":"friendlyEmptyPoolPath","type":"bool","internalType":"bool"},{"name":"feeTaken","type":"uint256","internalType":"uint256"},{"name":"dust","type":"uint256","internalType":"uint256"},{"name":"metadataFrozenEmitted","type":"bool","internalType":"bool"}]}],"stateMutability":"view"},
{"type":"function","name":"getMarketAllowlist","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address[]","internalType":"address[]"}],"stateMutability":"view"},
{"type":"function","name":"getMarketDescription","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bytes","internalType":"bytes"}],"stateMutability":"view"},
{"type":"function","name":"getMarketOptions","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bytes[]","internalType":"bytes[]"}],"stateMutability":"view"},
{"type":"function","name":"getMarketParticipants","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"address[]","internalType":"address[]"}],"stateMutability":"view"},
{"type":"function","name":"getMarketStreamUrl","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bytes","internalType":"bytes"}],"stateMutability":"view"},
{"type":"function","name":"getMarketTitle","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bytes","internalType":"bytes"}],"stateMutability":"view"},
{"type":"function","name":"getOptionFirstStakeSequence","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"optionIndex","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"sequence","type":"uint16","internalType":"uint16"},{"name":"isSet","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"getOptionPool","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"optionIndex","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"getPendingClaim","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"wallet","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"getStakerStake","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"wallet","type":"address","internalType":"address"},{"name":"optionIndex","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"getVoteResolution","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"topN","type":"uint256[]","internalType":"uint256[]"},{"name":"topNStakes","type":"uint256[]","internalType":"uint256[]"},{"name":"sumOfTopNStakes","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"nextMarketId","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"resolve","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"outcome","type":"uint8","internalType":"uint8"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"stake","inputs":[{"name":"marketId","type":"uint256","internalType":"uint256"},{"name":"optionIndex","type":"uint256","internalType":"uint256"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"treasury","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
{"type":"function","name":"usdc","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract IERC20"}],"stateMutability":"view"},
{"type":"function","name":"userClaimed","inputs":[{"name":"","type":"uint256","internalType":"uint256"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"event","name":"Canceled","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"reason","type":"uint8","indexed":false,"internalType":"uint8"}],"anonymous":false},
{"type":"event","name":"Claimed","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"recipient","type":"address","indexed":true,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"DistributedPrizePool","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"topN","type":"uint256[]","indexed":false,"internalType":"uint256[]"},{"name":"winnerWallets","type":"address[]","indexed":false,"internalType":"address[]"},{"name":"amountsOwed","type":"uint256[]","indexed":false,"internalType":"uint256[]"},{"name":"feeTaken","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"MarketCreated","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"creator","type":"address","indexed":true,"internalType":"address"},{"name":"marketShape","type":"uint8","indexed":false,"internalType":"uint8"},{"name":"createdAt","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"stakingOpensAt","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"closeAt","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"visibilityView","type":"uint8","indexed":false,"internalType":"uint8"},{"name":"visibilityParticipation","type":"uint8","indexed":false,"internalType":"uint8"},{"name":"clientNonce","type":"bytes32","indexed":false,"internalType":"bytes32"}],"anonymous":false},
{"type":"event","name":"MarketMetadataFrozen","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"frozenAt","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"ResolvedFriendly","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"outcome","type":"uint8","indexed":false,"internalType":"uint8"},{"name":"emptyPoolPath","type":"bool","indexed":false,"internalType":"bool"},{"name":"feeTaken","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"totalOwed","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"ResolvedOpenVote","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"topN","type":"uint256[]","indexed":false,"internalType":"uint256[]"},{"name":"feeTaken","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"Staked","inputs":[{"name":"marketId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"staker","type":"address","indexed":true,"internalType":"address"},{"name":"optionIndex","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"timestamp","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"error","name":"AlreadyClaimed","inputs":[]},
{"type":"error","name":"AlreadyVoted","inputs":[]},
{"type":"error","name":"AmountAboveCap","inputs":[]},
{"type":"error","name":"AmountBelowFloor","inputs":[]},
{"type":"error","name":"BadDecimals","inputs":[]},
{"type":"error","name":"CreatorActionInvalidState","inputs":[]},
{"type":"error","name":"CreatorWindowClosed","inputs":[]},
{"type":"error","name":"ERC20TransferFailed","inputs":[]},
{"type":"error","name":"ERC20TransferFromFailed","inputs":[]},
{"type":"error","name":"EditWindowClosed","inputs":[]},
{"type":"error","name":"InvalidAllowlist","inputs":[]},
{"type":"error","name":"InvalidOptions","inputs":[]},
{"type":"error","name":"InvalidOutcome","inputs":[]},
{"type":"error","name":"InvalidParticipants","inputs":[]},
{"type":"error","name":"InvalidShape","inputs":[]},
{"type":"error","name":"InvalidStakeBounds","inputs":[]},
{"type":"error","name":"InvalidTimestamps","inputs":[]},
{"type":"error","name":"InvalidWinners","inputs":[]},
{"type":"error","name":"MarketUnknown","inputs":[]},
{"type":"error","name":"MetadataFreezeNotReady","inputs":[]},
{"type":"error","name":"MetadataTooLarge","inputs":[]},
{"type":"error","name":"NoStakesToSettle","inputs":[]},
{"type":"error","name":"NotAllowlisted","inputs":[]},
{"type":"error","name":"NotCreator","inputs":[]},
{"type":"error","name":"NotInTerminalState","inputs":[]},
{"type":"error","name":"NothingToClaim","inputs":[]},
{"type":"error","name":"NothingToFinalize","inputs":[]},
{"type":"error","name":"StakingClosed","inputs":[]},
{"type":"error","name":"StakingNotOpen","inputs":[]},
{"type":"error","name":"TransferAmountMismatch","inputs":[]},
{"type":"error","name":"TreasuryNotAllowed","inputs":[]},
{"type":"error","name":"WalletCapExceeded","inputs":[]},
{"type":"error","name":"WrongShape","inputs":[]},
{"type":"error","name":"ZeroAddress","inputs":[]},
] as const;
